// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type MyModule
func (r *Binding) AsMyModule() *MyModule { // my-module (../../../../modules/my-module/main.go:22:6)
	q := r.query.Select("asMyModule")

	return &MyModule{
		query: q,
	}
}

// Create or update a binding of type MyModule in the environment
func (r *Env) WithMyModuleInput(name string, value *MyModule, description string) *Env { // my-module (../../../../modules/my-module/main.go:22:6)
	assertNotNil("value", value)
	q := r.query.Select("withMyModuleInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired MyModule output to be assigned in the environment
func (r *Env) WithMyModuleOutput(name string, description string) *Env { // my-module (../../../../modules/my-module/main.go:22:6)
	q := r.query.Select("withMyModuleOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type MyModule struct { // my-module (../../../../modules/my-module/main.go:22:6)
	query *querybuilder.Selection

	grepDir *string
	id      *ID
	print   *string
}

func (r *MyModule) WithGraphQLQuery(q *querybuilder.Selection) *MyModule {
	return &MyModule{
		query: q,
	}
}

// Returns a container that echoes whatever string argument is provided
func (r *MyModule) ContainerEcho(stringArg string) *Container { // my-module (../../../../modules/my-module/main.go:25:1)
	q := r.query.Select("containerEcho")
	q = q.Arg("stringArg", stringArg)

	return &Container{
		query: q,
	}
}

// Returns lines that match a pattern in the files of the provided Directory
func (r *MyModule) GrepDir(ctx context.Context, directoryArg *Directory, pattern string) (string, error) { // my-module (../../../../modules/my-module/main.go:34:1)
	assertNotNil("directoryArg", directoryArg)
	if r.grepDir != nil {
		return *r.grepDir, nil
	}
	q := r.query.Select("grepDir")
	q = q.Arg("directoryArg", directoryArg)
	q = q.Arg("pattern", pattern)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this MyModule.
func (r *MyModule) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *MyModule) XXX_GraphQLType() string {
	return "MyModule"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *MyModule) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *MyModule) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *MyModule) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *MyModule) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = MyModule{query: selectNode(dag.query, id, "MyModule")}
	return nil
}

func (r *MyModule) Print(ctx context.Context, stringArg string) (string, error) { // my-module (../../../../modules/my-module/main.go:29:1)
	if r.print != nil {
		return *r.print, nil
	}
	q := r.query.Select("print")
	q = q.Arg("stringArg", stringArg)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this MyModule as a Node.
// This is a local type conversion — no GraphQL call.
func (r *MyModule) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// A generated module for MyModule functions
//
// This module has been generated via dagger module init and serves as a reference to
// basic module structure as you get started with Dagger.
//
// Two functions have been pre-created. You can modify, delete, or add to them,
// as needed. They demonstrate usage of arguments and return types using simple
// echo and grep commands. The functions can be called from the dagger CLI or
// from one of the SDKs.
//
// The first line in this comment block is a short description line and the
// rest is a long description with more detail on the module's purpose or usage,
// if appropriate. All modules should have a short description.
func (r *Query) MyModule() *MyModule { // my-module (../../../../modules/my-module/main.go:22:6)
	q := r.query.Select("myModule")

	return &MyModule{
		query: q,
	}
}
