// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type MyDep
func (r *Binding) AsMyDep() *MyDep { // my-dep (../../../../../.dagger/modules/my-dep/main.go:22:6)
	q := r.query.Select("asMyDep")

	return &MyDep{
		query: q,
	}
}

// Create or update a binding of type MyDep in the environment
func (r *Env) WithMyDepInput(name string, value *MyDep, description string) *Env { // my-dep (../../../../../.dagger/modules/my-dep/main.go:22:6)
	assertNotNil("value", value)
	q := r.query.Select("withMyDepInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired MyDep output to be assigned in the environment
func (r *Env) WithMyDepOutput(name string, description string) *Env { // my-dep (../../../../../.dagger/modules/my-dep/main.go:22:6)
	q := r.query.Select("withMyDepOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type MyDep struct { // my-dep (../../../../../.dagger/modules/my-dep/main.go:22:6)
	query *querybuilder.Selection

	grepDir *string
	id      *ID
}

func (r *MyDep) WithGraphQLQuery(q *querybuilder.Selection) *MyDep {
	return &MyDep{
		query: q,
	}
}

// Returns a container that echoes whatever string argument is provided
func (r *MyDep) ContainerEcho(stringArg string) *Container { // my-dep (../../../../../.dagger/modules/my-dep/main.go:25:1)
	q := r.query.Select("containerEcho")
	q = q.Arg("stringArg", stringArg)

	return &Container{
		query: q,
	}
}

// Returns lines that match a pattern in the files of the provided Directory
func (r *MyDep) GrepDir(ctx context.Context, directoryArg *Directory, pattern string) (string, error) { // my-dep (../../../../../.dagger/modules/my-dep/main.go:30:1)
	assertNotNil("directoryArg", directoryArg)
	if r.grepDir != nil {
		return *r.grepDir, nil
	}
	q := r.query.Select("grepDir")
	q = q.Arg("directoryArg", directoryArg)
	q = q.Arg("pattern", pattern)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this MyDep.
func (r *MyDep) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *MyDep) XXX_GraphQLType() string {
	return "MyDep"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *MyDep) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *MyDep) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *MyDep) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *MyDep) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = MyDep{query: selectNode(dag.query, id, "MyDep")}
	return nil
}

// AsNode returns this MyDep as a Node.
// This is a local type conversion — no GraphQL call.
func (r *MyDep) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// A generated module for MyDep functions
//
// This module has been generated via dagger module init and serves as a reference to
// basic module structure as you get started with Dagger.
//
// Two functions have been pre-created. You can modify, delete, or add to them,
// as needed. They demonstrate usage of arguments and return types using simple
// echo and grep commands. The functions can be called from the dagger CLI or
// from one of the SDKs.
//
// The first line in this comment block is a short description line and the
// rest is a long description with more detail on the module's purpose or usage,
// if appropriate. All modules should have a short description.
func (r *Query) MyDep() *MyDep { // my-dep (../../../../../.dagger/modules/my-dep/main.go:22:6)
	q := r.query.Select("myDep")

	return &MyDep{
		query: q,
	}
}
