// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"

	"dagger.io/dagger/querybuilder"
)

type MyModule struct { // my-module (../../../../../:0:0)
	query *querybuilder.Selection

	grepDir *string
	print   *string
}

func (r *MyModule) WithGraphQLQuery(q *querybuilder.Selection) *MyModule {
	return &MyModule{
		query: q,
	}
}

// Returns a container that echoes whatever string argument is provided
func (r *MyModule) ContainerEcho(stringArg string) *Container {
	q := r.query.Select("containerEcho")
	q = q.Arg("stringArg", stringArg)

	return &Container{
		query: q,
	}
}

// MyModuleGrepDirOpts contains options for MyModule.GrepDir
type MyModuleGrepDirOpts struct {
	DirectoryArg Directory
}

// Returns lines that match a pattern in the files of the provided Directory
func (r *MyModule) GrepDir(ctx context.Context, pattern string, opts ...MyModuleGrepDirOpts) (string, error) {
	if r.grepDir != nil {
		return *r.grepDir, nil
	}
	q := r.query.Select("grepDir")
	for i := len(opts) - 1; i >= 0; i-- {
		// `directoryArg` optional argument
		if !querybuilder.IsZeroValue(opts[i].DirectoryArg) {
			q = q.Arg("directoryArg", opts[i].DirectoryArg)
		}
	}
	q = q.Arg("pattern", pattern)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *MyModule) Print(ctx context.Context, stringArg string) (string, error) {
	if r.print != nil {
		return *r.print, nil
	}
	q := r.query.Select("print")
	q = q.Arg("stringArg", stringArg)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *Query) MyModule() *MyModule { // my-module (../../../../../:0:0)
	q := r.query.Select("myModule")

	return &MyModule{
		query: q,
	}
}
