// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type MyDep struct { // my-dep (../../../../../:0:0)
	query *querybuilder.Selection

	grepDir *string
	id      *ID
}

func (r *MyDep) WithGraphQLQuery(q *querybuilder.Selection) *MyDep {
	return &MyDep{
		query: q,
	}
}

// Returns a container that echoes whatever string argument is provided
func (r *MyDep) ContainerEcho(stringArg string) *Container {
	q := r.query.Select("containerEcho")
	q = q.Arg("stringArg", stringArg)

	return &Container{
		query: q,
	}
}

// Returns lines that match a pattern in the files of the provided Directory
func (r *MyDep) GrepDir(ctx context.Context, directoryArg *Directory, pattern string) (string, error) {
	assertNotNil("directoryArg", directoryArg)
	if r.grepDir != nil {
		return *r.grepDir, nil
	}
	q := r.query.Select("grepDir")
	q = q.Arg("directoryArg", directoryArg)
	q = q.Arg("pattern", pattern)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this MyDep.
func (r *MyDep) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *MyDep) XXX_GraphQLType() string {
	return "MyDep"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *MyDep) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *MyDep) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *MyDep) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *MyDep) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = MyDep{query: selectNode(dag.query, id, "MyDep")}
	return nil
}

func (r *Query) MyDep() *MyDep { // my-dep (../../../../../:0:0)
	q := r.query.Select("myDep")

	return &MyDep{
		query: q,
	}
}
